# Generated by Django 6.0.2 on 2026-02-09 10:44

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouprequest',
            old_name='to_user',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='grouprequest',
            old_name='from_user',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='status',
        ),
        migrations.AlterUniqueTogether(
            name='grouprequest',
            unique_together={('sender', 'recipient')},
        ),
        migrations.AddField(
            model_name='grouprequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='grouprequest',
            name='group',
        ),
    ]
