# Generated by Django 6.0.2 on 2026-02-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_group_assigned_guide_and_more'),
    ]

    operations = []
