# Generated by Django 6.0.2 on 2026-02-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_group_assigned_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='coordinator_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='abstract',
            name='guide_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='abstract',
            name='is_final_approved',
            field=models.BooleanField(default=False),
        ),
    ]
