# Generated by Django 5.2.11 on 2026-02-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_abstract_id_alter_coordinatorapproval_id_and_more'),
        ('core', '0014_remove_sustainabledevelopmentgoal_content_and_more'),
    ]

    operations = [
    ]
