# Generated by Django 5.2.10 on 2026-02-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20260227_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='sustainabledevelopmentgoal',
            name='project_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sustainabledevelopmentgoal',
            name='project_title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coordinatorapproval',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='grouprequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='guiderequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='po1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='po2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='po3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='po4',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='po5',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='pso1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='pso2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='sdg1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='sdg1_justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='sdg2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='sdg2_justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='sdg3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='sdg3_justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='sdg4',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='sdg4_justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='sdg5',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='sdg5_justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='wp1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='wp1_justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='wp2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='wp2_justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='wp3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='wp3_justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='wp4',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='wp4_justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='wp5',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='wp5_justification',
            field=models.TextField(blank=True, default=''),
        ),
    ]
