# Generated by Django 5.1.6 on 2026-03-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_sustainabledevelopmentgoal_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='cgp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
