# Generated by Django 5.2.10 on 2026-03-09 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_studentprofile_cgp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='final_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='abstract',
            name='hod_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='abstract',
            name='presentation_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='is_hod',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('coordinator_forward', 'Coordinator Forwarded Project'), ('presentation_ready', 'Project Ready for Presentation Approval'), ('final_approval', 'Final Project Requires Approval')], default='coordinator_forward', max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_abstract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.abstract')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
