# Generated by Django 5.2.11 on 2026-03-07 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_abstract_id_alter_coordinatorapproval_id_and_more'),
        ('core', '0017_studentprofile_cgp'),
    ]

    operations = [
    ]
