# Generated by Django 6.0.2 on 2026-03-10 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_abstract_final_approved_abstract_hod_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('zeroth', 'Zeroth Evaluation'), ('first', 'First Evaluation'), ('second', 'Second Evaluation'), ('final', 'Final Evaluation')], max_length=10)),
                ('guide_technical_exposure', models.BooleanField(default=False)),
                ('guide_socially_relevant', models.BooleanField(default=False)),
                ('guide_product_based', models.BooleanField(default=False)),
                ('guide_research_oriented', models.BooleanField(default=False)),
                ('coordinator_technical_exposure', models.BooleanField(default=False)),
                ('coordinator_socially_relevant', models.BooleanField(default=False)),
                ('coordinator_product_based', models.BooleanField(default=False)),
                ('coordinator_research_oriented', models.BooleanField(default=False)),
                ('guide_submitted', models.BooleanField(default=False)),
                ('coordinator_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.group')),
            ],
            options={
                'ordering': ['group', 'stage'],
                'unique_together': {('group', 'stage')},
            },
        ),
    ]
