# Generated by Django 6.0.2 on 2026-03-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_evaluationfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupevaluation',
            name='coordinator_review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupevaluation',
            name='guide_review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
