# Generated by Django 6.0.2 on 2026-03-10 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_groupevaluation_coordinator_review_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('first', 'First Evaluation'), ('second', 'Second Evaluation')], max_length=10)),
                ('guide_topic', models.IntegerField(blank=True, help_text='Topic identification / literature survey (5)', null=True)),
                ('guide_planning', models.IntegerField(blank=True, help_text='Project planning / scheduling / resources / innovative design (5)', null=True)),
                ('guide_scalability', models.IntegerField(blank=True, help_text='Scalability and reliability (2)', null=True)),
                ('guide_novelty', models.IntegerField(blank=True, help_text='Novelty of idea and implementation scope (5)', null=True)),
                ('guide_task_distribution', models.IntegerField(blank=True, help_text='Task distribution among team members (5)', null=True)),
                ('guide_schedule', models.IntegerField(blank=True, help_text='Adherence to project schedule (3)', null=True)),
                ('guide_interim', models.IntegerField(blank=True, help_text='Interim results (5)', null=True)),
                ('guide_presentation', models.IntegerField(blank=True, help_text='Presentation (5)', null=True)),
                ('guide_viva', models.IntegerField(blank=True, help_text='Viva (5)', null=True)),
                ('guide_submitted', models.BooleanField(default=False)),
                ('coordinator_topic', models.IntegerField(blank=True, help_text='Topic identification / literature survey (5)', null=True)),
                ('coordinator_planning', models.IntegerField(blank=True, help_text='Project planning / scheduling / resources / innovative design (5)', null=True)),
                ('coordinator_scalability', models.IntegerField(blank=True, help_text='Scalability and reliability (2)', null=True)),
                ('coordinator_novelty', models.IntegerField(blank=True, help_text='Novelty of idea and implementation scope (5)', null=True)),
                ('coordinator_task_distribution', models.IntegerField(blank=True, help_text='Task distribution among team members (5)', null=True)),
                ('coordinator_schedule', models.IntegerField(blank=True, help_text='Adherence to project schedule (3)', null=True)),
                ('coordinator_interim', models.IntegerField(blank=True, help_text='Interim results (5)', null=True)),
                ('coordinator_presentation', models.IntegerField(blank=True, help_text='Presentation (5)', null=True)),
                ('coordinator_viva', models.IntegerField(blank=True, help_text='Viva (5)', null=True)),
                ('coordinator_submitted', models.BooleanField(default=False)),
                ('finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_evaluations', to='core.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['stage', 'student__username'],
                'unique_together': {('student', 'stage')},
            },
        ),
    ]
