# Generated by Django 6.0.2 on 2026-03-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_studentevaluation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentevaluation',
            options={'ordering': ['group', 'stage', 'student']},
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator_interim',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator_novelty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator_planning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator_presentation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator_scalability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator_schedule',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator_task_distribution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator_topic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator_viva',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='guide_interim',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='guide_novelty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='guide_planning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='guide_presentation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='guide_scalability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='guide_schedule',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='guide_task_distribution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='guide_topic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='guide_viva',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
