# Generated by Django 6.0.2 on 2026-03-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_class_abstract_coordinator1_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='class_name',
        ),
    ]
