# Generated by Django 6.0.2 on 2026-03-24 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_cie_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentevaluation',
            name='attendance_marks',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='cie_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='committee_mark',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='committee_raw_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator1_interim',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator1_novelty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator1_planning',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator1_presentation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator1_scalability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator1_schedule',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator1_task_distribution',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator1_topic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator1_viva',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator2_interim',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator2_novelty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator2_planning',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator2_presentation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator2_scalability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator2_schedule',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator2_task_distribution',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator2_topic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator2_viva',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator_interim',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator_novelty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator_planning',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator_presentation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator_scalability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator_schedule',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator_task_distribution',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator_topic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='coordinator_viva',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='final_guide_interim',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='final_guide_mark',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='final_guide_novelty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='final_guide_planning',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='final_guide_presentation',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='final_guide_raw',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='final_guide_scale',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='final_guide_schedule',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='final_guide_task',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='final_guide_topic',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='final_guide_total',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='final_guide_viva',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='guide_interim',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='guide_novelty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='guide_planning',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='guide_presentation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='guide_scalability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='guide_schedule',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='guide_task_distribution',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='guide_topic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='guide_viva',
            field=models.IntegerField(default=0),
        ),
    ]
