# Generated by Django 6.0.2 on 2026-03-24 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_update_null_evaluation_fields_to_zero'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentevaluation',
            name='ese_guide_demo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='ese_guide_presentation',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='ese_guide_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='ese_guide_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='ese_guide_viva',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)]),
        ),
    ]
