# Generated by Django 6.0.2 on 2026-03-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_ese_coordinator_fields_and_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentevaluation',
            name='ese_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='ese_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='final_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='result_calculated',
            field=models.BooleanField(default=False),
        ),
    ]
