# Generated by Django 6.0.2 on 2026-03-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_studentevaluation_ese_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentevaluation',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='studentevaluation',
            name='percentage',
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='final_grade',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='final_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
