# Generated by Django 6.0.2 on 2026-03-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_studentevaluation_final_results'),
        ('core', '0039_remove_studentevaluation_grade_and_more'),
    ]

    operations = [
    ]
