# Generated by Django 6.0.2 on 2026-03-24 18:33

import django.core.validators
from django.db import migrations, models


LEGACY_COLUMNS = [
    "ese_coord1_total",
    "ese_coord2_total",
    "ese_final_mark",
    "grade",
    "percentage",
]


def drop_legacy_columns(apps, schema_editor):
    StudentEvaluation = apps.get_model('core', 'StudentEvaluation')
    table = StudentEvaluation._meta.db_table
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        existing_columns = {
            info.name
            for info in connection.introspection.get_table_description(cursor, table)
        }
    for column in LEGACY_COLUMNS:
        if column not in existing_columns:
            continue
        schema_editor.execute(
            f"ALTER TABLE {schema_editor.quote_name(table)} DROP COLUMN {schema_editor.quote_name(column)}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_merge_20260324_1832'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='studentevaluation',
                    name='ese_coord1_total',
                ),
                migrations.RemoveField(
                    model_name='studentevaluation',
                    name='ese_coord2_total',
                ),
                migrations.RemoveField(
                    model_name='studentevaluation',
                    name='ese_final_mark',
                ),
                migrations.RemoveField(
                    model_name='studentevaluation',
                    name='grade',
                ),
                migrations.RemoveField(
                    model_name='studentevaluation',
                    name='percentage',
                ),
            ],
            database_operations=[
                migrations.RunPython(drop_legacy_columns, migrations.RunPython.noop)
            ],
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='ese_coord1_demo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='ese_coord1_presentation',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='ese_coord1_viva',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='ese_coord2_demo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='ese_coord2_presentation',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='ese_coord2_viva',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)]),
        ),
    ]
